In [26]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ahmed\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ahmed\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ahmed\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [29]:
df = pd.read_csv("customer_complaints_1.csv")
df.head()

,author,posted_on,rating,text
0,"Alantae of Chesterfeild, MI","Nov. 22, 2016",1,I used to love Comcast. Until all these consta...
1,"Vera of Philadelphia, PA","Nov. 19, 2016",1,I'm so over Comcast! The worst internet provid...
2,"Sarah of Rancho Cordova, CA","Nov. 17, 2016",1,If I could give them a negative star or no sta...
3,"Dennis of Manchester, NH","Nov. 16, 2016",1,I've had the worst experiences so far since in...
4,"Ryan of Bellevue, WA","Nov. 14, 2016",1,Check your contract when you sign up for Comca...

In [30]:
df.columns.tolist()

['author', 'posted_on', 'rating', 'text']

In [31]:
text_col = 'text'
texts = df[text_col].dropna().astype(str).tolist()

print("Using column:", text_col)
print("Number of documents:", len(texts))
print(texts[0])

Using column: text
Number of documents: 19
I used to love Comcast. Until all these constant updates. My internet and cable crash a lot at night, and sometimes during the day, some channels don't even work and on demand sometimes don't play either. I wish they will do something about it. Because just a few mins ago, the internet have crashed for about 20 mins for no reason. I'm tired of it and thinking about switching to Wow or something. Please do not get Xfinity.

In [32]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [33]:
clean_texts = [preprocess(text) for text in texts]

print("Original:")
print(texts[0])
print("\nPreprocessed:")
print(clean_texts[0])

Original:
I used to love Comcast. Until all these constant updates. My internet and cable crash a lot at night, and sometimes during the day, some channels don't even work and on demand sometimes don't play either. I wish they will do something about it. Because just a few mins ago, the internet have crashed for about 20 mins for no reason. I'm tired of it and thinking about switching to Wow or something. Please do not get Xfinity.

Preprocessed:
used love comcast constant update internet cable crash lot night sometimes day channel dont even work demand sometimes dont play either wish something min ago internet crashed min reason im tired thinking switching wow something please get xfinity

In [34]:
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(clean_texts)

k = 3
kmeans_tfidf = KMeans(n_clusters=k, random_state=42, n_init=10)
tfidf_labels = kmeans_tfidf.fit_predict(X_tfidf)

print("TF-IDF clustering completed.")

TF-IDF clustering completed.

In [35]:
order_centroids = kmeans_tfidf.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names_out()

for i in range(k):
    print(f"Cluster {i}:")
    top_terms = [terms[ind] for ind in order_centroids[i, :10]]
    print(", ".join(top_terms))
    print()

Cluster 0:
comcast, service, time, would, customer, month, since, second, adding, im

Cluster 1:
contract, speed, internet, mbps, xfinity, customer, told, service, would, tech

Cluster 2:
rude, rep, service, day, joke, charge, local, fee, people, bill

In [36]:
df_tfidf = df.dropna(subset=[text_col]).copy()
df_tfidf['Cluster_TFIDF'] = tfidf_labels
df_tfidf[[text_col, 'Cluster_TFIDF']].head(10)

                                                text  Cluster_TFIDF
0  I used to love Comcast. Until all these consta...              1
1  I'm so over Comcast! The worst internet provid...              0
2  If I could give them a negative star or no sta...              0
3  I've had the worst experiences so far since in...              0
4  Check your contract when you sign up for Comca...              1
5  Thank God. I am changing to Dish. They gave me...              0
6  I Have been a long time customer and only have...              1
7  There is a malfunction on the DVR manager whic...              0
8  Charges overwhelming. Comcast service rep was ...              2
9  I have had cable, DISH, and U-verse, etc. in t...              0

In [37]:
from gensim.models import Word2Vec

In [38]:
tokenized_texts = [text.split() for text in clean_texts]

In [39]:
word2vec_model = Word2Vec(
    sentences=tokenized_texts,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

print("Word2Vec model trained.")

Word2Vec model trained.

In [40]:
X_w2v = []
for doc in tokenized_texts:
    vectors = [word2vec_model.wv[word] for word in doc if word in word2vec_model.wv]
    if len(vectors) > 0:
        doc_vector = np.mean(vectors, axis=0)
    else:
        doc_vector = np.zeros(100)
    X_w2v.append(doc_vector)

X_w2v = np.array(X_w2v)
print("Word2Vec vectors shape:", X_w2v.shape)

Word2Vec vectors shape: (19, 100)

In [41]:
kmeans_w2v = KMeans(n_clusters=k, random_state=42, n_init=10)
w2v_labels = kmeans_w2v.fit_predict(X_w2v)

print("Word2Vec clustering completed.")

Word2Vec clustering completed.

C:\Users\ahmed\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [42]:
df_w2v = df.dropna(subset=[text_col]).copy()
df_w2v['Cluster_Word2Vec'] = w2v_labels
df_w2v[[text_col, 'Cluster_Word2Vec']].head(10)

                                                text  Cluster_Word2Vec
0  I used to love Comcast. Until all these consta...                 1
1  I'm so over Comcast! The worst internet provid...                 0
2  If I could give them a negative star or no sta...                 0
3  I've had the worst experiences so far since in...                 0
4  Check your contract when you sign up for Comca...                 1
5  Thank God. I am changing to Dish. They gave me...                 0
6  I Have been a long time customer and only have...                 0
7  There is a malfunction on the DVR manager whic...                 0
8  Charges overwhelming. Comcast service rep was ...                 2
9  I have had cable, DISH, and U-verse, etc. in t...                 0

In [43]:
print("TF-IDF cluster counts:")
print(df_tfidf['Cluster_TFIDF'].value_counts())

print("\nWord2Vec cluster counts:")
print(df_w2v['Cluster_Word2Vec'].value_counts())

TF-IDF cluster counts:
Cluster_TFIDF
1    9
0    7
2    3
Name: count, dtype: int64

Word2Vec cluster counts:
Cluster_Word2Vec
0    16
1     2
2     1
Name: count, dtype: int64

In [44]:
df_result = df.dropna(subset=[text_col]).copy()
df_result['Cleaned_Text'] = clean_texts
df_result['Cluster_TFIDF'] = tfidf_labels
df_result['Cluster_Word2Vec'] = w2v_labels

df_result.head(10)

,author,posted_on,rating,text,Cleaned_Text,Cluster_TFIDF,Cluster_Word2Vec
0,"Alantae of Chesterfeild, MI","Nov. 22, 2016",1,I used to love Comcast. Until all these consta...,used love comcast constant update internet cab...,1,1
1,"Vera of Philadelphia, PA","Nov. 19, 2016",1,I'm so over Comcast! The worst internet provid...,im comcast worst internet provider im taking o...,0,0
2,"Sarah of Rancho Cordova, CA","Nov. 17, 2016",1,If I could give them a negative star or no sta...,could give negative star star review would nev...,0,0
3,"Dennis of Manchester, NH","Nov. 16, 2016",1,I've had the worst experiences so far since in...,ive worst experience far since install nothing...,0,0
4,"Ryan of Bellevue, WA","Nov. 14, 2016",1,Check your contract when you sign up for Comca...,check contract sign comcast advertised offer m...,1,1
5,"Terri of Mobile, AL","Nov. 9, 2016",1,Thank God. I am changing to Dish. They gave me...,thank god changing dish gave awesome pricing s...,0,0
6,"Kellie of Salt Lake City, UT","Nov. 9, 2016",1,I Have been a long time customer and only have...,long time customer xfinity isp local walmart n...,1,0
7,"Kathleen of New Haven, CT","Nov. 6, 2016",2,There is a malfunction on the DVR manager whic...,malfunction dvr manager preventing u adding re...,0,0
8,"Shira of Bloomfield, NJ","Nov. 5, 2016",1,Charges overwhelming. Comcast service rep was ...,charge overwhelming comcast service rep ignora...,2,2
9,"Kristy of Alpharetta, GA","Nov. 2, 2016",1,"I have had cable, DISH, and U-verse, etc. in t...",cable dish uverse etc past eh know comcast tak...,0,0

In [45]:
df_result.to_csv("customer_complaints_clustered.csv", index=False)
print("File saved as customer_complaints_clustered.csv")

File saved as customer_complaints_clustered.csv

In [46]:
for i in range(k):
    print(f"\n===== TF-IDF Cluster {i} Sample Documents =====")
    sample_docs = df_result[df_result['Cluster_TFIDF'] == i][text_col].head(5).tolist()
    for j, doc in enumerate(sample_docs, 1):
        print(f"{j}. {doc}")

===== TF-IDF Cluster 0 Sample Documents =====
1. I'm so over Comcast! The worst internet provider. I'm taking online classes and multiple times was late with my assignments because of the power interruptions in my area that lead to poor quality internet service. Definitely switching to Verizon. I'd rather pay $10 extra then dealing w/ Comcast and non stopping internet problems.
2. If I could give them a negative star or no stars on this review I would. I have never worked with any industry with as bad of customer service as Comcast. It is not a matter of money because I make well enough above and beyond to afford their services but they are a legitimate ripoff. I think they are the biggest scam of since the mortgage industry's major meltdown and I hope I move somewhere where Comcast does not exist. The disregard to want to help or do the right thing is honestly astounding. If you have to call, which you do FOR ALL ISSUES - billing, connection/service, adding or removing service, errors, it does not matter you will be transferred minimum of 4 times. Everyone says the same thing and passes the issues to the next person and no one resolves the problem.They offer promotional packages in small timeframes and can never access them again so they then upgrade you without you wishing and change your billing. It has been 5 months and I have been overcharged $40 a month since I started with them. The blatant rudeness that must make you qualified to do this job is the type of quality service that gets you this review. So... Dear Comcast, you suck. Sincerely, a customer who cannot wait to never use your service again.
3. I've had the worst experiences so far since install on 10/4/16. Nothing but problems. Two no shows on scheduled service appointments, extreme difficulty in adding boxes to the second floor. What is so difficult about adding boxes to an existing account? No thank you, I'm not starting a second account for the second floor of the same house! A separate bundle package? All I wanted was just to add a few boxes. Apparently this is not possible. Well then, I guess it's not possible to remain a customer!
4. Thank God. I am changing to Dish. They gave me awesome pricing and super people to deal with. You can actually understand what they are saying. I'm so excited to finally be able to return this equipment although still haven't received the home security yet as promised 4 times. Go to h*ll Comcast. You have made me miserable and cause me to miss many hours of work with your promises.
5. There is a malfunction on the DVR manager which is preventing us from adding more recordings. Customer service is fairly certain that the problem is from the signal from their system to ours, but protocol demands that they access our home before investigating that option. Since we work, that cannot be done until next Saturday. Customer service tech agreed that this seems illogical since logic would dictate that one would investigate the most probably malfunction first, but insists they must follow protocol. This is extremely frustrating. After 35 years as a customer of Comcast & their predecessors, I am investigating alternatives.

===== TF-IDF Cluster 1 Sample Documents =====
1. I used to love Comcast. Until all these constant updates. My internet and cable crash a lot at night, and sometimes during the day, some channels don't even work and on demand sometimes don't play either. I wish they will do something about it. Because just a few mins ago, the internet have crashed for about 20 mins for no reason. I'm tired of it and thinking about switching to Wow or something. Please do not get Xfinity.
2. Check your contract when you sign up for Comcast as their advertised offers do not match the contract they issue. I signed up for $49.99 150Mbps internet for 2 years, however my contract has $19.99 for 25Mbps internet for 2 years. They say there is an add on in place for $30 which boost it to Blast! Pro, however this isn't part of the contract, which means that Comcast can increase the price whenever they want within the 2 years. This means I haven't received the advertised rate. Comcast has so far refused to issue corrected contract, or issue in writing that the $30 will remain at that price for 2 years. I just have to trust them. So watch out, Comcast is doing the usual illegal practices, I'm guessing to catch people out and hope they don't notice and end up paying more than they should.
3. I Have been a long time customer and only have Xfinity as my ISP for a while now. While I was in the local Walmart on November 4, 2016, there were customer representatives from Xfinity running promotions for and in the Salt Lake City area. Spoke with a representative and was able to get and signed a contract for Pro Blast at $50.00 a month with no contract or early termination fees. I received an email from Xfinity stating the changes that would be made to my account. It stated that not only would it be under contract for 24 months but there would be early termination fees. This is not what I had originally signed up for and it specifically states this on the contract that I signed. Contacted Xfinity customer service and was told since they cannot see the contract over the phone that I would need to go to Xfinity store in person. Went to Xfinity store on November 8, 2016 and was told that it would be under contract and there was no way around it. Because of this I have cancelled the upgrade and went back to my original plan. It's plain and simple. When a contract is signed it should be honored for what is stated on it. Xfinity is dishonest and not trustworthy. Therefore I will be looking and changing my ISP as soon as possible to another company. Xfinity does not deserve a paycheck from me or anyone else that I know.
4. Had them from 2014 to now. I'd tell new customers to run but there is nowhere to run to. I tried, but it turned out Comcast was Xfinity. Signing up for a contract has no meaning. The fine print in the contract that they suggest you read when they randomly change a contract says they can change anything anytime and are not doing anything wrong. I disagree. I have or had performance pro, paying for a speed of internet a month under a contract. Not month to month alone. The speed is not listed or told to you just it's between 25 and 50.I got a letter Friday saying Tue (today) I'm being forced into a new contract plan. I'm now paying for my data at the same speed with a cap of a terabyte. Seems like a lot but it's not and not what I signed up for. But all customer service says is that's the deal now. They don't offer plans by just speed it's changed. Those who use more Internet should pay more. It's not fair to the other customers. What does it matter fair it's what we signed up to use. I use firestick. We stream everything all day. It's frustrating. They kept saying it's the same, but if I use more just go to the unlimited plan for only $50 more. I don't have 150$. It's why we got rid of direcTV for firestick. Paying for an unlimited speed to being changed to pay for data is a huge difference. All they can say is, "You won't know there was a change unless you go over 1000. The closest you got so far was 980 and we won't charge you for going over the first 2 months to get used to it." When I first went to talk to someone at the store they didn't want to talk to me and told me I needed to call billing. They don't know about it. How can they not help or explain if we pay bills there and get equipment there. After a minute the guy called someone over who is good at explaining the letter. So now they know about the letter and someone can explain it. They just didn't want to deal with it in the store. So the other guy comes over and lies to us as well. Tells us the letter got sent to everyone but is only for new customers, not us. Whatever I know it's all a lie. We leave and today I call Comcast. As soon as you call it asks if you are calling about your data. Say yes and it directs the call to someone who only knows to say, "Read your contract and there is nothing you can do." They don't know anything. You need billing. Then why did it put the call to somewhere that can't help. It's the run around. The last guy I talked to is what is above. How can they be the only internet around. So I'm forced to pay by data now and I don't even get a better speed for being gypped. It's also wrong - I only got notified Friday. That Tuesday Nov 1st the change takes effect.
5. Disappointed. I have been a Comcast/Xfinity customer for almost two decades. I pay for high speeds and get intermittent internet. I call every week almost-- can't take the time to call more often and get FRUSTRATED. I spend 30 minutes with the first person resetting the modem (walking through their initial process - even after giving them the history) only to be told I will have to pay for a technician. After some complaining and explaining - they transfer me to a specialist who does speed tests and confirms what I am saying even though their test "say" the modem is working - he test each port on the modem (which is a new modem they replaced last week) and I have the same issue - tells me there is a line issue and my modem isn't performing correctly - technician reprograms the ports--retests it works awesome initially when they get it to carry more data--only to retest with the technician a few minutes later and the speed is low again. They say they need to send out a tech to look at the lines - COLD transfer me back to Xfinity without warning and when someone answers they start the process ALL OVER AGAIN - reset the modem charge me for tech - transfer me to specialist - another 3 hours wasted this week, last week - in this modern age and for $216 a month you would think you could work from home without distractions. I pay for the fastest package 115 mbps download and 25 mbps upload and receive random speeds throughout the day (between 9-80 mbps download and 2-22 mbps) upload - most often in the lower numbers with wireless monitoring showing "dropped" messages from my server and having to refresh pages and lose data regularly. Is there anyone out there who can help? I am attaching several speed tests from today during my calls between 10-12 a.m cst. What does a consumer do? Is there a dependable internet provider? It feels like they use their call systems to bully/frustrate the customer into submission.

===== TF-IDF Cluster 2 Sample Documents =====
1. Charges overwhelming. Comcast service rep was so ignorant and rude when I call to resolve my issue with my bill. I emailed Tom ** his rep was rude to me. None of the representative was helpful. They all just pass me on to other people. I am cutting my service with Comcast.
2. Unplanned, unexpected, all day outages, rude service reps. Rearranging my day to set up service only to deal with a totally inept technician who has to call for backup on another day. I could go on, but why? We are dropping this failure of a company and relying on hotspots from now on.
3. BE WARNED. You will have 10$ hidden fees when you sign up for this service. They charge you extra for the local news stations and a fee for local sports that you will not be told about until you see it on your first bill. The customer service people are a JOKE and rude rude rude. If you ask for a manager they will get snotty and never let you talk to one... I know they have attractive packages to get you hooked but it's a joke and you will pay more in the long run than the competitors.

In [47]:
for i in range(k):
    print(f"\n===== Word2Vec Cluster {i} Sample Documents =====")
    sample_docs = df_result[df_result['Cluster_Word2Vec'] == i][text_col].head(5).tolist()
    for j, doc in enumerate(sample_docs, 1):
        print(f"{j}. {doc}")

===== Word2Vec Cluster 0 Sample Documents =====
1. I'm so over Comcast! The worst internet provider. I'm taking online classes and multiple times was late with my assignments because of the power interruptions in my area that lead to poor quality internet service. Definitely switching to Verizon. I'd rather pay $10 extra then dealing w/ Comcast and non stopping internet problems.
2. If I could give them a negative star or no stars on this review I would. I have never worked with any industry with as bad of customer service as Comcast. It is not a matter of money because I make well enough above and beyond to afford their services but they are a legitimate ripoff. I think they are the biggest scam of since the mortgage industry's major meltdown and I hope I move somewhere where Comcast does not exist. The disregard to want to help or do the right thing is honestly astounding. If you have to call, which you do FOR ALL ISSUES - billing, connection/service, adding or removing service, errors, it does not matter you will be transferred minimum of 4 times. Everyone says the same thing and passes the issues to the next person and no one resolves the problem.They offer promotional packages in small timeframes and can never access them again so they then upgrade you without you wishing and change your billing. It has been 5 months and I have been overcharged $40 a month since I started with them. The blatant rudeness that must make you qualified to do this job is the type of quality service that gets you this review. So... Dear Comcast, you suck. Sincerely, a customer who cannot wait to never use your service again.
3. I've had the worst experiences so far since install on 10/4/16. Nothing but problems. Two no shows on scheduled service appointments, extreme difficulty in adding boxes to the second floor. What is so difficult about adding boxes to an existing account? No thank you, I'm not starting a second account for the second floor of the same house! A separate bundle package? All I wanted was just to add a few boxes. Apparently this is not possible. Well then, I guess it's not possible to remain a customer!
4. Thank God. I am changing to Dish. They gave me awesome pricing and super people to deal with. You can actually understand what they are saying. I'm so excited to finally be able to return this equipment although still haven't received the home security yet as promised 4 times. Go to h*ll Comcast. You have made me miserable and cause me to miss many hours of work with your promises.
5. I Have been a long time customer and only have Xfinity as my ISP for a while now. While I was in the local Walmart on November 4, 2016, there were customer representatives from Xfinity running promotions for and in the Salt Lake City area. Spoke with a representative and was able to get and signed a contract for Pro Blast at $50.00 a month with no contract or early termination fees. I received an email from Xfinity stating the changes that would be made to my account. It stated that not only would it be under contract for 24 months but there would be early termination fees. This is not what I had originally signed up for and it specifically states this on the contract that I signed. Contacted Xfinity customer service and was told since they cannot see the contract over the phone that I would need to go to Xfinity store in person. Went to Xfinity store on November 8, 2016 and was told that it would be under contract and there was no way around it. Because of this I have cancelled the upgrade and went back to my original plan. It's plain and simple. When a contract is signed it should be honored for what is stated on it. Xfinity is dishonest and not trustworthy. Therefore I will be looking and changing my ISP as soon as possible to another company. Xfinity does not deserve a paycheck from me or anyone else that I know.

===== Word2Vec Cluster 1 Sample Documents =====
1. I used to love Comcast. Until all these constant updates. My internet and cable crash a lot at night, and sometimes during the day, some channels don't even work and on demand sometimes don't play either. I wish they will do something about it. Because just a few mins ago, the internet have crashed for about 20 mins for no reason. I'm tired of it and thinking about switching to Wow or something. Please do not get Xfinity.
2. Check your contract when you sign up for Comcast as their advertised offers do not match the contract they issue. I signed up for $49.99 150Mbps internet for 2 years, however my contract has $19.99 for 25Mbps internet for 2 years. They say there is an add on in place for $30 which boost it to Blast! Pro, however this isn't part of the contract, which means that Comcast can increase the price whenever they want within the 2 years. This means I haven't received the advertised rate. Comcast has so far refused to issue corrected contract, or issue in writing that the $30 will remain at that price for 2 years. I just have to trust them. So watch out, Comcast is doing the usual illegal practices, I'm guessing to catch people out and hope they don't notice and end up paying more than they should.

===== Word2Vec Cluster 2 Sample Documents =====
1. Charges overwhelming. Comcast service rep was so ignorant and rude when I call to resolve my issue with my bill. I emailed Tom ** his rep was rude to me. None of the representative was helpful. They all just pass me on to other people. I am cutting my service with Comcast.

In [48]:
print("Conclusion:")
print("Text preprocessing was added before TF-IDF and Word2Vec vectorization.")
print("Then KMeans clustering was applied on the complaint texts from customer_complaints_1.csv.")

Conclusion:
Text preprocessing was added before TF-IDF and Word2Vec vectorization.
Then KMeans clustering was applied on the complaint texts from customer_complaints_1.csv.

Text preprocessing was added before both TF-IDF and Word2Vec vectorization. The preprocessing included lowercasing, removing symbols, removing stopwords, and lemmatization. After that, KMeans clustering was applied to the complaint texts from customer_complaints_1.csv. The clustering results show how similar complaint texts can be grouped together based on their content. In general, preprocessing helps improve clustering quality because it removes noise and keeps more meaningful words for vectorization.